import { StyleSheet } from 'react-native';

export const COLORS = {
  background: '#2D2D2D',
  accent: '#FFA500',
  roteiro: '#00A9A5', 
  text: '#F5F5F5',
  textSecondary: '#A0A0A0',
  cardBackground: '#393939',
  alertBackground: 'rgba(255, 221, 99, 0.1)', 
  alertBorder: '#FFDD63',
  navInactive: '#8E8E93',
  navBackground: '#1E1E1E',
  optionBorder: '#555555',
  // Cores específicas para melhor contraste
  textContrast: '#1A1A1A',
  textSecondaryContrast: '#4A4A4A',
  borderContrast: '#CCCCCC',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.navBackground,
  },
  mainContentWrapper: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  headerContainer: {
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTextContainer: {
    flex: 1,
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileButtonText: {
    fontSize: 18,
    fontFamily: 'Poppins_600SemiBold',
  },
  mainTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 22,
    color: COLORS.text,
  },
  subTitle: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  saveButton: {
    backgroundColor: COLORS.accent,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 20,
    marginLeft: 16,
  },
  saveButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: COLORS.background,
  },
  titleContainer: {
    marginBottom: 20,
  },
  titleLabel: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 8,
    marginLeft: 4,
  },
  dayTitleInput: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 18,
    color: COLORS.roteiro,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.accent,
    paddingBottom: 8,
    backgroundColor: 'rgba(255, 165, 0, 0.1)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.accent,
  },
  scrollView: {
    paddingHorizontal: 20,
  },
  itineraryItemContainer: {
    flexDirection: 'row',
  },
  timelineContainer: {
    width: 50,
    alignItems: 'center',
  },
  timeText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  iconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.cardBackground,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  timelineLine: {
    flex: 1,
    width: 2,
    backgroundColor: COLORS.cardBackground,
    marginTop: -8, 
  },
  contentContainer: {
    flex: 1,
    paddingLeft: 12,
    paddingBottom: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemTextContainer: {
    flex: 1,
  },
  itemTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 4,
  },
  itemDescription: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  itemAddress: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
    lineHeight: 16,
  },
  itemActionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editButtonsContainer: {
    flexDirection: 'row',
    marginRight: 8,
  },
  editButton: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 6,
    padding: 6,
    marginHorizontal: 2,
    minWidth: 32,
    alignItems: 'center',
  },
  editButtonDisabled: {
    backgroundColor: COLORS.optionBorder,
    opacity: 0.5,
  },
  editButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: COLORS.text,
  },
  editButtonTextDisabled: {
    color: COLORS.textSecondary,
  },
  editControlsContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    gap: 12,
  },
  editModeButton: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.optionBorder,
  },
  editModeButtonActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  editModeButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: COLORS.text,
  },
  editModeButtonTextActive: {
    color: COLORS.background,
  },
  optimizeButton: {
    backgroundColor: COLORS.roteiro,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  optimizeButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: COLORS.text,
  },
  timeTextEditable: {
    backgroundColor: COLORS.accent,
    color: COLORS.background,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    fontFamily: 'Poppins_700Bold',
  },
  locationPhoto: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  editTimeLabel: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 16,
    textAlign: 'center',
  },
  timeInput: {
    backgroundColor: COLORS.background,
    color: COLORS.text,
    fontFamily: 'Montserrat_500Medium',
    borderRadius: 10,
    padding: 12,
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: COLORS.optionBorder,
  },
  saveTimeButton: {
    backgroundColor: COLORS.accent,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  saveTimeButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.background,
  },
  imageModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageModalContent: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    padding: 20,
    margin: 20,
    maxHeight: '90%',
    width: '90%',
  },
  imageModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  imageModalTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 18,
    color: COLORS.text,
    flex: 1,
    marginRight: 16,
  },
  imageModalCloseButton: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 24,
    color: COLORS.textSecondary,
    padding: 8,
  },
  imageContainer: {
    alignItems: 'center',
  },
  expandedImage: {
    width: '100%',
    height: 300,
    borderRadius: 12,
    marginBottom: 12,
  },
  imageModalAddress: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  locationPreviewContainer: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    alignItems: 'center',
  },
  locationPreviewTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  locationPreviewAddress: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: 12,
  },
  locationPreviewImage: {
    width: 120,
    height: 80,
    borderRadius: 8,
  },
  timeSelectionContainer: {
    marginBottom: 20,
  },
  timeSelectionLabel: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 12,
  },
  timeInput: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    fontFamily: 'Montserrat_500Medium',
    color: COLORS.text,
    borderWidth: 1,
    borderColor: COLORS.optionBorder,
    textAlign: 'center',
  },
  timeSelectionHint: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginTop: 8,
  },
  // Estilos para o modal de detalhes do local
  loadingContainer: {
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 16,
    color: COLORS.text,
    marginTop: 16,
  },
  detailsContainer: {
    maxHeight: '80%',
  },
  detailsSection: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.optionBorder,
  },
  detailsTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 20,
    color: COLORS.text,
    marginBottom: 8,
  },
  sectionTitle: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 8,
  },
  detailsText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 20,
  },
  statusContainer: {
    marginBottom: 16,
  },
  statusText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    textAlign: 'center',
  },
  statusOpen: {
    backgroundColor: '#E8F5E8',
    color: '#2E7D32',
  },
  statusClosed: {
    backgroundColor: '#FFEBEE',
    color: '#D32F2F',
  },
  statusUnknown: {
    backgroundColor: '#F5F5F5',
    color: COLORS.textSecondary,
  },
  ratingContainer: {
    marginBottom: 12,
  },
  ratingText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
  },
  priceContainer: {
    marginBottom: 12,
  },
  priceText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
  },
  scheduleText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  accessibilityContainer: {
    marginTop: 8,
  },
  accessibilityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 8,
  },
  accessibilityIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  accessibilityText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
  accessibilityAvailable: {
    color: '#2E7D32',
  },
  accessibilityUnavailable: {
    color: '#D32F2F',
  },
  contactText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 4,
  },
  descriptionText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
    lineHeight: 22,
    textAlign: 'justify',
  },
  historyText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 22,
    fontStyle: 'italic',
  },
  photosContainer: {
    marginTop: 8,
  },
  detailPhoto: {
    width: 200,
    height: 150,
    borderRadius: 8,
    marginRight: 12,
  },
  reviewContainer: {
    backgroundColor: COLORS.cardBackground,
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  reviewAuthor: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 14,
    color: COLORS.text,
    marginBottom: 4,
  },
  reviewRating: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    color: COLORS.accent,
    marginBottom: 8,
  },
  reviewText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 18,
    marginBottom: 8,
  },
  reviewDate: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 11,
    color: COLORS.textSecondary,
  },
  errorContainer: {
    alignItems: 'center',
    padding: 40,
  },
  errorText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 16,
    color: COLORS.textSecondary,
  },
  timeSelectionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  cancelTimeButton: {
    flex: 1,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.optionBorder,
  },
  cancelTimeButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: COLORS.text,
    textAlign: 'center',
  },
  confirmTimeButton: {
    flex: 1,
    backgroundColor: COLORS.accent,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  confirmTimeButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: COLORS.background,
    textAlign: 'center',
  },
  removeButton: {
    padding: 8,
    marginLeft: 8,
  },
  footerContainer: {},
  alertContainer: {
    backgroundColor: COLORS.alertBackground,
    borderColor: COLORS.alertBorder,
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 24,
  },
  alertText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 13,
    color: COLORS.alertBorder,
    flex: 1,
    marginLeft: 12,
    lineHeight: 18,
  },
  addButton: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  addButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.text,
    marginLeft: 8,
  },
  navContainer: {
    flexDirection: 'row',
    paddingTop: 10,
    paddingBottom: 20, 
    backgroundColor: COLORS.navBackground,
    borderTopWidth: 1,
    borderTopColor: COLORS.cardBackground,
  },
  navButton: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navLabel: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 10,
    marginTop: 4,
  },

  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.cardBackground,
    height: '80%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 20,
    color: COLORS.text,
  },
  closeButtonText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 16,
    color: COLORS.accent,
  },
  searchInput: {
    backgroundColor: COLORS.background,
    color: COLORS.text,
    fontFamily: 'Montserrat_500Medium',
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    marginBottom: 20,
  },
  searchResultItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.optionBorder,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  searchResultTextContainer: {
    flex: 1,
  },
  searchResultTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.text,
  },
  searchResultDescription: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  addResultButton: {
    backgroundColor: COLORS.accent,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginLeft: 16,
  },
  addResultButtonText: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 14,
    color: COLORS.background,
  },
  emptySearchText: {
    textAlign: 'center',
    fontFamily: 'Montserrat_500Medium',
    color: COLORS.textSecondary,
    marginTop: 40,
  },
  mapWrapper: {
    flex: 1,
  },
  sortRowContainer: {
    position: 'relative',
  },
  sortRow: {
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  sortRowContent: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 12,
  },
  sortButton: {
    backgroundColor: COLORS.cardBackground,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'transparent',
    marginHorizontal: 4,
    minWidth: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sortButtonActive: {
    borderColor: COLORS.accent,
  },
  sortButtonText: {
    fontFamily: 'Montserrat_500Medium',
    color: COLORS.text,
    fontSize: 12,
    textAlign: 'center',
    flexShrink: 1,
  },
  sortButtonTextActive: {
    color: COLORS.accent,
  },
  mapInfoContainer: {
    backgroundColor: COLORS.cardBackground,
    padding: 12,
    margin: 10,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.accent,
  },
  mapInfoContainerFiltered: {
    backgroundColor: '#FFF3E0',
    borderLeftColor: '#FF9800',
    borderWidth: 1,
    borderColor: '#FFE0B2',
  },
  mapInfoTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 4,
  },
  mapInfoSubtitle: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  clearFiltersContainer: {
    paddingHorizontal: 12,
    paddingBottom: 8,
    alignItems: 'center',
  },
  clearFiltersButton: {
    backgroundColor: COLORS.background,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearFiltersText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 12,
    color: COLORS.accent,
  },
  // Estilos para o Radar
  radarWrapper: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  radarHeader: {
    padding: 20,
    paddingTop: 10,
  },
  radarTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 24,
    color: COLORS.text,
    marginBottom: 8,
  },
  radarSubtitle: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 16,
    color: COLORS.textSecondary,
    lineHeight: 22,
  },
  filterSection: {
    marginBottom: 20,
  },
  filterLabel: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 10,
  },
  filterRow: {
    flexDirection: 'row',
  },
  filterChip: {
    backgroundColor: COLORS.background,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  filterChipActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  filterChipText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    color: COLORS.text,
  },
  filterChipTextActive: {
    color: COLORS.background,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ratingButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ratingButtonActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  ratingText: {
    fontSize: 16,
  },
  ratingTextActive: {
    color: COLORS.background,
  },
  ratingLabel: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
    marginLeft: 10,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  priceButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceButtonActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  priceText: {
    fontSize: 16,
  },
  priceTextActive: {
    color: COLORS.background,
  },
  priceLabel: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
    marginLeft: 10,
  },
  accessibilityContainer: {
    flexDirection: 'row',
  },
  accessibilityButton: {
    backgroundColor: COLORS.background,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  accessibilityButtonActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  accessibilityText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
  },
  accessibilityTextActive: {
    color: COLORS.background,
  },
  statusContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  statusButton: {
    backgroundColor: COLORS.background,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    flex: 1,
    alignItems: 'center',
  },
  statusButtonActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  statusText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
  },
  statusTextActive: {
    color: COLORS.background,
  },
  sliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 15,
  },
  sliderLabel: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    color: COLORS.textSecondary,
    minWidth: 30,
  },
  sliderTrack: {
    flex: 1,
    height: 6,
    backgroundColor: COLORS.border,
    borderRadius: 3,
    position: 'relative',
  },
  sliderProgress: {
    height: 6,
    backgroundColor: COLORS.accent,
    borderRadius: 3,
  },
  sliderThumb: {
    position: 'absolute',
    top: -10,
    width: 24,
    height: 24,
    backgroundColor: COLORS.accent,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: COLORS.background,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sliderThumbActive: {
    width: 28,
    height: 28,
    top: -12,
    borderRadius: 14,
    borderWidth: 4,
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 8,
  },
  quickControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 10,
  },
  quickButton: {
    backgroundColor: COLORS.background,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    flex: 1,
    alignItems: 'center',
  },
  quickButtonText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 12,
    color: COLORS.text,
  },
  radarSearchButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  radarSearchButtonText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
    color: COLORS.background,
  },
  radarMapContainer: {
    flex: 1,
    margin: 10,
    borderRadius: 10,
    overflow: 'hidden',
  },
  radarMapInfo: {
    backgroundColor: COLORS.cardBackground,
    padding: 12,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.accent,
  },
  radarMapTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 4,
  },
  radarMapSubtitle: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  radarMap: {
    flex: 1,
  },
  radarMapPlaceholder: {
    flex: 1,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radarMapPlaceholderText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 16,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  // Novos estilos baseados na imagem
  distanceSection: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: COLORS.cardBackground,
    marginHorizontal: 20,
    borderRadius: 12,
    marginBottom: 20,
  },
  distanceLabel: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 15,
  },
  distanceValue: {
    color: COLORS.accent,
    fontWeight: 'bold',
  },
  foundSection: {
    flex: 1,
    paddingHorizontal: 20,
  },
  foundHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  foundTitle: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 18,
    color: COLORS.text,
  },
  sortDropdownContainer: {
    position: 'relative',
    zIndex: 1000,
  },
  sortDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  sortText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
    marginRight: 5,
  },
  sortArrow: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  sortDropdownMenu: {
    position: 'absolute',
    top: 40,
    right: 0,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    minWidth: 180,
    zIndex: 1001,
  },
  sortOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  sortOptionActive: {
    backgroundColor: COLORS.accent + '20',
  },
  sortOptionIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  sortOptionText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.text,
    flex: 1,
  },
  sortOptionTextActive: {
    color: COLORS.accent,
    fontFamily: 'Montserrat_600SemiBold',
  },
  locationsList: {
    flex: 1,
  },
  locationCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.cardBackground,
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  locationIcon: {
    width: 50,
    height: 50,
    backgroundColor: COLORS.background,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
    overflow: 'hidden',
  },
  locationImage: {
    width: 50,
    height: 50,
    borderRadius: 8,
  },
  locationIconText: {
    fontSize: 24,
  },
  locationInfo: {
    flex: 1,
  },
  locationName: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 4,
  },
  locationType: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  locationDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  locationDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  detailIcon: {
    fontSize: 12,
  },
  detailText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  noResultsContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  noResultsText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 16,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: 20,
  },
  searchButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  searchButtonText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 14,
    color: COLORS.background,
  },
  map: {
    flex: 1,
  },
  placeholderWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderText: {
    fontFamily: 'Montserrat_500Medium',
    color: COLORS.textSecondary,
  },
  // Estilos para Rota Cronológica
  routeSection: {
    backgroundColor: COLORS.cardBackground,
    margin: 15,
    padding: 15,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.accent,
  },
  routeTitle: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 18,
    color: COLORS.text,
    marginBottom: 5,
  },
  routeSubtitle: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 15,
  },
  routeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 8,
  },
  routeNumber: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  routeNumberText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 14,
    color: '#000',
  },
  routeContent: {
    flex: 1,
  },
  routeTime: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
    color: COLORS.accent,
    marginBottom: 2,
  },
  routeName: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 15,
    color: COLORS.text,
    marginBottom: 2,
  },
  routeAddress: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 12,
    color: COLORS.textSecondary,
  },


  // Estilos para Tela de Usuário
  profileContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  authContainer: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  authHeader: {
    alignItems: 'center',
    marginBottom: 40,
  },
  authTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: 10,
  },
  authSubtitle: {
    fontSize: 16,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  authButtons: {
    marginBottom: 40,
  },
  authButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    marginBottom: 15,
    alignItems: 'center',
  },
  registerButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: COLORS.accent,
  },
  authButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.background,
  },
  registerButtonText: {
    color: COLORS.accent,
  },
  authFeatures: {
    backgroundColor: COLORS.cardBackground,
    padding: 20,
    borderRadius: 15,
  },
  featuresTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 15,
    textAlign: 'center',
  },
  featuresList: {
    gap: 10,
  },
  featureItem: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 8,
  },

  // Estilos para Usuário Logado
  userContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  userHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: COLORS.cardBackground,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.optionBorder,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 4,
  },
  userEmail: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  logoutButton: {
    backgroundColor: COLORS.optionBorder,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 15,
  },
  logoutButtonText: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: '600',
  },
  userContent: {
    flex: 1,
    padding: 20,
  },
  sectionContainer: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: 15,
  },
  emptySection: {
    backgroundColor: COLORS.cardBackground,
    padding: 30,
    borderRadius: 15,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  routesList: {
    gap: 15,
  },
  routeCard: {
    backgroundColor: COLORS.cardBackground,
    padding: 15,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  routeCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  routeCardName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.text,
    flex: 1,
  },
  routeCardDate: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  routeCardLocations: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: COLORS.cardBackground,
    padding: 20,
    borderRadius: 15,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.accent,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },

  // Estilos para Modais de Autenticação
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  authModalContainer: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    width: '90%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  authModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.optionBorder,
  },
  authModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  authModalContent: {
    padding: 20,
  },
  authInput: {
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.optionBorder,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 15,
  },
  authSubmitButton: {
    backgroundColor: COLORS.accent,
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 15,
  },
  authSubmitButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.background,
  },
  authSwitchButton: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  authSwitchButtonText: {
    fontSize: 14,
    color: COLORS.accent,
  },
  // Estilos para alternância de tema
  titleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  themeToggle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  themeToggleText: {
    fontSize: 20,
  },
  // Estilos para dica de segurança
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  securityTipButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  securityTipButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  securityTipContent: {
    padding: 20,
  },
  securityTipText: {
    fontFamily: 'Montserrat_500Medium',
    fontSize: 16,
    color: COLORS.text,
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 20,
  },
  securityTipFooter: {
    alignItems: 'center',
  },
  securityTipSource: {
    fontFamily: 'Montserrat_400Regular',
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 20,
    textAlign: 'center',
  },
  securityTipActions: {
    flexDirection: 'row',
    gap: 12,
  },
  securityTipCloseButton: {
    backgroundColor: COLORS.accent,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  securityTipCloseButtonText: {
    fontFamily: 'Montserrat_600SemiBold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  // Estilos para card de dica de segurança
  securityTipCard: {
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 10,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  securityTipNeighborhood: {
    fontSize: 12,
    marginTop: 8,
    fontStyle: 'italic',
    opacity: 0.8,
  },
  alertNeighborhood: {
    fontSize: 12,
    marginTop: 8,
    fontStyle: 'italic',
    opacity: 0.8,
  },
  // Estilos do modal de salvar roteiro
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    padding: 24,
    borderRadius: 16,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: 'Poppins_700Bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
    marginBottom: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  modalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  cancelButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: 'Poppins_600SemiBold',
  },
  saveModalButton: {
    // backgroundColor será definido dinamicamente
  },
  saveModalButtonText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Poppins_600SemiBold',
  },
});
